app: shifang-ffmpeg-composition-sync
component: scf
inputs:
  cls:
    logsetId: 7cb1c8d7-0a91-452f-95fe-78441855e24c
    topicId: 2c81e19a-4d49-489f-892f-c13dcf17bab1
  description: helloworld 空白模板函数
  eip: false
  events:
    - apigw:
        parameters:
          endpoints:
            - apiId: api-7t14q4sh
              enableCORS: false
              function:
                functionQualifier: $DEFAULT
                isIntegratedResponse: false
              isBase64Encoded: false
              method: ANY
              path: /shifang-ffmpeg-composition-sync
              serviceTimeout: 30
          environment: release
          protocols:
            - http
            - https
          serviceId: service-ngvp1ppd
          serviceName: SCF_API_SERVICE
  handler: index.main_handler
  initTimeout: 65
  memorySize: 3072
  msgTTL: 21600
  name: shifang-ffmpeg-composition-sync
  namespace: shifang
  publicAccess: true
  region: ap-chengdu
  retryNum: 2
  role: SCF_ExecuteRole
  runtime: Python3.7
  src: ./
  timeout: 30
  type: event
name: ap-chengdu_shifang_shifang-ffmpeg-composition-sync
org: '1307427535'
stage: dev
# When using this configuration file for deployment, make sure the file name is "serverless.yml".
# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md